version: '2'
services:
    db:
        image: ilios/mysql-demo
        ports:
            - "17103:3306"
    web:
        image: ilios/php-apache
        ports:
            - "8000:80"
        volumes:
            - ./logs:/var/www/ilios/var/logs:rw
