version: '2'
services:
    db:
        image: ilios/mysql-demo
        ports:
            - "17103:3306"
    web:
        image: ilios/php-apache-dev
        environment:
            - ILIOS_REQUIRE_SECURE_CONNECTION=false
        ports:
            - "8000:80"
