version: '2'
services:
    db:
        image: ilios/mysql-demo
        ports:
            - "17103:3306"
    web:
        image: ilios/php-apache-dev
        environment:
            - APP_ENV=dev
            - APP_DEBUG=true
            - ILIOS_DATABASE_URL=mysql://ilios:ilios@db/ilios
            - ILIOS_REQUIRE_SECURE_CONNECTION=false
            - ILIOS_ERROR_CAPTURE_ENABLED=false
            - ILIOS_ELASTICSEARCH_HOSTS=elasticsearch
            - ILIOS_FILE_SYSTEM_STORAGE_PATH=/tmp
        ports:
            - "8000:80"
    elasticsearch:
        image: elasticsearch:7.6.2
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
